name: Deploy Frontend Marihuanas

on:
  push:
    branches:
      - master

concurrency:
  group: deploy-frontend-marihuanas
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: self-hosted
    env:
      NODE_OPTIONS: "--max-old-space-size=4096"
      CI: "false"
      GENERATE_SOURCEMAP: "false"
    steps:
      - name: Deploy and Build
        run: |
          cd /var/www/apps/frontend-marihuanas
          git fetch origin
          git reset --hard origin/master
          npm install --legacy-peer-deps --no-audit
          npm run build
